<?php
$title = "رستوران";
$username = "نام کاربری";
$password = "رمز عبور";
$password1 = "تکرار رمز عبور";
$enter = "ورود به سامانه";
$email = "رایانامه";
$logout = "ثبت نام";
$login = "ورود";
$exit = "خروج";
$fa = "فارسی";
$en = "english";
$change = "تغییر بده";
$deser = "دسر";
$deser_des = "دسر توت فرنگی ...";
$fish = "ماهی";
$fish_des = "ماهی گزل آلا ...";
$jooje = "جوجه";
$jooje_des = "جوجه کباب مخصوص ...";
$link = "<link rel=\"stylesheet\" href=\"https://cdn.rtlcss.com/bootstrap/v4.0.0/css/bootstrap.min.css\" integrity=\"sha384-P4uhUIGk/q1gaD/NdgkBIl3a6QywJjlsFJFk7SPRdruoGddvRVSwv5qFnvZ73cpz\" crossorigin=\"anonymous\">";
$personal = "مشخصات شخصی";
$fname = "نام";
$lname = "نام خانوادگی";
$phone = "تلفن";
$address= "آدرس";
$userinf = "مشخصات کاربری";
$locationinf = "مشخصات ارتباطی";
$plus = "اضافه به سبد خرید";
$pop = "حذف از سبد خرید";

